spring:
  application:
    name: client-service
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true
      discovery:
        enabled: true
        service-id: config-server1
  config:
    import: "optional:configserver:"
  sleuth:
    sampler:
      probability: 1
    integration:
      enabled: true
  zipkin:
    enabled: true
    base-url: http://192.168.99.102:9411
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}
server:
  port: 8082
feign:
  circuitbreaker:
    enabled: true

logging:
  file:
    path: E:\Java\WorkTools\logs